name: SpawnTweaks
version: 1.2.10
description: Tweaks spawning behavior of mobs.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-spawntweaks/
main: com.moltendorf.bukkit.spawntweaks.Plugin
